/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    products: Product;
    collections: Collection;
    categories: Category;
    orders: Order;
    messages: Message;
    media: Media;
    pages: Page;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    products: ProductsSelect<false> | ProductsSelect<true>;
    collections: CollectionsSelect<false> | CollectionsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * Adres /urun/<buraya> şeklinde oluşur. Boş bırakırsanız başlıktan otomatik üretilir.
   */
  slug: string;
  categories?: (number | Category)[] | null;
  collection?: (number | null) | Collection;
  /**
   * İlk görsel liste ve paylaşımlarda kapak olur.
   */
  images: (number | Media)[];
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  material?: string | null;
  dimensions?: string | null;
  hasVariants?: boolean | null;
  /**
   * KURUŞ cinsinden tam sayı girin. Örn: 7.900,00 TL için 790000 yazın.
   */
  basePrice?: number | null;
  stock?: number | null;
  variants?:
    | {
        metal?: ('silver' | 'gold') | null;
        size?: ('small' | 'medium' | 'large') | null;
        /**
         * KURUŞ cinsinden tam sayı girin. Örn: 7.900,00 TL için 790000 yazın.
         */
        price: number;
        stock: number;
        sku?: string | null;
        id?: string | null;
      }[]
    | null;
  isActive?: boolean | null;
  isFeatured?: boolean | null;
  seo?: {
    metaTitle?: string | null;
    /**
     * Google sonuçlarında görünen metin. ~155 karakter.
     */
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * Mevcut siteyle aynı kalmalı: kolye, kupe, yuzuk, erkekkolye, erkekyuzuk. Boş bırakırsanız başlıktan otomatik üretilir.
   */
  slug: string;
  cover?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Görselde ne olduğunu yazın. Ekran okuyucular ve Google için gerekli. Örn: “Gümüş Kelt kolye, yakın çekim”.
   */
  alt: string;
  /**
   * İsteğe bağlı. Fotoğrafçı adı.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections".
 */
export interface Collection {
  id: number;
  title: string;
  /**
   * Mevcut sitedeki adresle birebir aynı olmalı (kelt, cosmos, yerkure …). Değiştirmek Google sıralamasını kaybettirir. Boş bırakırsanız başlıktan otomatik üretilir.
   */
  slug: string;
  cover?: (number | null) | Media;
  /**
   * Koleksiyonun arkasındaki hikâye. Ürün sayfalarında da gösterilir.
   */
  story?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber: string;
  status: 'pending' | 'paid' | 'preparing' | 'shipped' | 'delivered' | 'cancelled' | 'refunded' | 'failed';
  customer: {
    firstName: string;
    lastName: string;
    email: string;
    phone: string;
  };
  shippingAddress: {
    line1: string;
    district: string;
    city: string;
    postalCode?: string | null;
  };
  billingSameAsShipping?: boolean | null;
  billingAddress?: {
    line1?: string | null;
    district?: string | null;
    city?: string | null;
    postalCode?: string | null;
  };
  /**
   * Fiyatlar sipariş anında kopyalanmıştır; ürün fiyatı sonradan değişse bile burası değişmez.
   */
  items: {
    product?: (number | null) | Product;
    titleSnapshot: string;
    variantLabel?: string | null;
    unitPrice: number;
    quantity: number;
    lineTotal: number;
    id?: string | null;
  }[];
  subtotal: number;
  shippingCost: number;
  total: number;
  /**
   * Sunucu tarafından doldurulur, elle değiştirmeyin.
   */
  payment?: {
    conversationId?: string | null;
    token?: string | null;
    paymentId?: string | null;
    paidAt?: string | null;
    installment?: number | null;
  };
  /**
   * Mesafeli Satış Sözleşmesi ve Ön Bilgilendirme Formu'nun kabul edildiği an. Yasal kayıt.
   */
  contractAcceptedAt?: string | null;
  shipping?: {
    carrier?: string | null;
    trackingNumber?: string | null;
    shippedAt?: string | null;
  };
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: number;
  name: string;
  status?: ('new' | 'answered' | 'closed') | null;
  email: string;
  phone?: string | null;
  subject?: ('general' | 'custom' | 'appointment' | 'order') | null;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Yasal sayfalar mevcut adreslerini korumalı: kvkk, gizlilik, mesafelisatis, teslimatveiade. Boş bırakırsanız başlıktan otomatik üretilir.
   */
  slug: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'collections';
        value: number | Collection;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'messages';
        value: number | Message;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  categories?: T;
  collection?: T;
  images?: T;
  description?: T;
  material?: T;
  dimensions?: T;
  hasVariants?: T;
  basePrice?: T;
  stock?: T;
  variants?:
    | T
    | {
        metal?: T;
        size?: T;
        price?: T;
        stock?: T;
        sku?: T;
        id?: T;
      };
  isActive?: T;
  isFeatured?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_select".
 */
export interface CollectionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  cover?: T;
  story?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  cover?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  status?: T;
  customer?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        email?: T;
        phone?: T;
      };
  shippingAddress?:
    | T
    | {
        line1?: T;
        district?: T;
        city?: T;
        postalCode?: T;
      };
  billingSameAsShipping?: T;
  billingAddress?:
    | T
    | {
        line1?: T;
        district?: T;
        city?: T;
        postalCode?: T;
      };
  items?:
    | T
    | {
        product?: T;
        titleSnapshot?: T;
        variantLabel?: T;
        unitPrice?: T;
        quantity?: T;
        lineTotal?: T;
        id?: T;
      };
  subtotal?: T;
  shippingCost?: T;
  total?: T;
  payment?:
    | T
    | {
        conversationId?: T;
        token?: T;
        paymentId?: T;
        paidAt?: T;
        installment?: T;
      };
  contractAcceptedAt?: T;
  shipping?:
    | T
    | {
        carrier?: T;
        trackingNumber?: T;
        shippedAt?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  name?: T;
  status?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  /**
   * Ana sayfanın en üstündeki tam ekran slider. Sıralamayı sürükleyerek değiştirebilirsiniz. İlk kare en hızlı yüklenen görsel olduğu için en güçlü fotoğrafı oraya koyun. Boş bırakılırsa slider gösterilmez.
   */
  hero?:
    | {
        /**
         * Yatay, en az 2000px genişlikte olmalı.
         */
        image: number | Media;
        /**
         * Örn: “Yeni Koleksiyon”
         */
        eyebrow?: string | null;
        title: string;
        subtitle?: string | null;
        linkLabel?: string | null;
        /**
         * Örn: /kelt
         */
        linkHref?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Ana sayfada üretim sürecini anlatan editoryal bölüm.
   */
  atelier?: {
    enabled?: boolean | null;
    image?: (number | null) | Media;
    title?: string | null;
    text?: string | null;
    linkLabel?: string | null;
    linkHref?: string | null;
  };
  contact?: {
    phone?: string | null;
    email?: string | null;
    address?: string | null;
    whatsapp?: string | null;
  };
  social?: {
    instagram?: string | null;
    facebook?: string | null;
  };
  shipping?: {
    /**
     * KURUŞ cinsinden. Örn: 150,00 TL için 15000.
     */
    flatRate?: number | null;
    /**
     * Bu tutarın üzerindeki siparişlerde kargo ücretsiz. Boş bırakılırsa ücretsiz kargo yok.
     */
    freeThreshold?: number | null;
  };
  /**
   * Mesafeli satış mevzuatı gereği sitede yayımlanması zorunlu bilgiler.
   */
  seller?: {
    legalName?: string | null;
    address?: string | null;
    taxOffice?: string | null;
    taxNumber?: string | null;
    mersis?: string | null;
  };
  announcement?: {
    enabled?: boolean | null;
    text?: string | null;
    link?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        image?: T;
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        linkLabel?: T;
        linkHref?: T;
        id?: T;
      };
  atelier?:
    | T
    | {
        enabled?: T;
        image?: T;
        title?: T;
        text?: T;
        linkLabel?: T;
        linkHref?: T;
      };
  contact?:
    | T
    | {
        phone?: T;
        email?: T;
        address?: T;
        whatsapp?: T;
      };
  social?:
    | T
    | {
        instagram?: T;
        facebook?: T;
      };
  shipping?:
    | T
    | {
        flatRate?: T;
        freeThreshold?: T;
      };
  seller?:
    | T
    | {
        legalName?: T;
        address?: T;
        taxOffice?: T;
        taxNumber?: T;
        mersis?: T;
      };
  announcement?:
    | T
    | {
        enabled?: T;
        text?: T;
        link?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}